name: Run tests
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install NPM packages
        run: npm ci
      - name: Lint JavaScript
        run: ./node_modules/.bin/eslint "resources/assets/javascripts/**/*.js"
      - name: Run PHP CodeSniffer
        run: ./vendor/bin/phpcs